### ISSUE TITLE
Pickup props

### ISSUE THREAD

**Issue by Flapchik** [swampservers/fatkid#8]
Please disable the ability to pick up props using the "E" key, because in this case, players on the gymnaium map can pick up chairs.
![image](https://user-images.githubusercontent.com/58729268/121803017-29724b80-cc48-11eb-99dc-5ba125e97b74.png)

**Comment by Flapchik** [comment]
I want to ask why only fatkid were forbidden to wear props?

**Comment by swampservers** [comment]
By design. Fatkid can't because they block too much damage that way
